version: 2
jobs:
  build:
    working_directory: ~/UserApi
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: 
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/UserApi
  install: 
    working_directory: ~/UserApi
    docker:
        - image: circleci/node:6.10.3
    steps:
        - run:
            name: save SHA to a file
            command: echo $CIRCLE_SHA1 > .circle-sha
        - restore_cache:
            keys:
              - v1-repo-{{ checksum ".circle-sha" }}
        - run: 
            name: install depencancies
            command: npm install
        - save_cache:
            key: v1-node-modules-{{ checksum ".circle-sha" }}
            paths:
              - ~/UserApi/node_modules
  lint: 
    working_directory: ~/UserApi
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run: 
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: v1-node-modules-{{ checksum ".circle-sha" }}
      - run:
          name: Linting
          command: npm run lint
  test:
    working_directory: ~/UserApi
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run: 
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: v1-node-modules-{{ checksum ".circle-sha" }}
      - run: 
          name: Create coverage directory
          command: mkdir -p ~/coverage
      - run:
          name: Unit Tests
          command: npm run ci
  coveralls: 
    working_directory: ~/UserApi
    docker:
      - image: circleci/node:6.10.3
    steps:
      - run: 
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          key: v1-node-modules-{{ checksum ".circle-sha" }}
      - run:
          name: Unit Tests
          command: npm run test:coveralls
workflows:
    version: 2
    build_accept_deploy:
        jobs:
            - build
            - install:
                requires:
                    - build
            - lint:
                requires:
                    - build
                    - install
            - test:
                requires:
                    - build
                    - install
            - coveralls:
                requires:
                    - build
                    - install
