version: 2
jobs:
  build:
    working_directory: ~/UserApi
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: make test dir
          command: mkdir -p ~/unit && mkdir -p ~/coverage
      - run:
          name: lint
          command: npm run lint
      - run:
          name: ci
          command: npm run ci
      - run:
          name: code-coverage
          command: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage