version: 2
jobs:
  build:
    working_directory: ~/UserApi
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
    run:
        name: install-npm-wee
        command: npm install
  lint:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  ci:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: npm install
      - run: npm run ci
  coveralls:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: npm install
      - run: 'NODE_ENV=test ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
      - ci
      - coveralls