ersion: 2
jobs:
  build:
    working_directory: ~/UserApi
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
  test1:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: npm run lint
  test2:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: npm run ci
  test3:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run: 'NODE_ENV=test ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
      - test2
      - test3